on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - run: zig version

      - name: Build
        run: zig build

      - name: Test
        run: zig build test

      - name: Fmt
        run: zig fmt --check src/*.zig
