name: ci
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - run: zig version

      - name: Install dependencies
        run: sudo apt install libcurl4-openssl-dev

      - name: Build
        run: zig build

      - name: Test
        run: zig build test

      - name: Build ReleaseSafe
        run: zig build -Doptimize=ReleaseSafe

      - name: Test ReleaseSafe
        run: zig build test -Doptimize=ReleaseSafe

      - name: Fmt
        run: zig fmt --check src/*.zig
